openapi: 3.1.0
info:
  title: OneSpot
  description: OneSpot aims to simplify and enhance the housing and social experiences for university students and young adults by providing a platform where users can easily find compatible housemates, post and discover various activities, and even verify housing options. We strive to save users time and effort, creating a sense of community and convenience.
  version: "v1.0"
servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: User endpoints
paths:
  /users:
    get:
      tags:
        - users
      summary: Fetch Users of OneSpot
      description: Fetch All Users of OneSpot
      operationId: getUsers
      responses:
        "200":
          description: List of Platform Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          description: Unauthenticated request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error401"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error500"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1200767
        firstName:
          type: string
          example: "Vishnu"
        lastName:
          type: string
          example: "Paduchuri"
        emailId:
          type: string
          example: "vispaduchuri@gmail.com"
        phoneNumber:
          type: string
          example: "+1(857)-701-6192"
    Error401:
      type: object
      properties:
        code:
          type: string
          description: Error Code
          examples:
            - AuthenticationError
        message:
          type: string
          description: Error Message
          examples:
            - User is not authenticated.
    Error500:
      type: object
      properties:
        code:
          type: string
          description: Error Code
          examples:
            - Internal Server Error
        message:
          type: string
          description: Error Message
          examples:
            - Internal Server Error.
